spring:
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/cca-test-db
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB


elasticsearch:
  datasource:
    host: localhost
    port: 9200
    fingerprint: ${ELASTIC_FINGERPRINT}
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
  query:
    timeout: 30s
