spring:
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/cca-test-db
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
#  sql:
#    init:
#      mode: always

logging:
  level:
    ru:
      turbogoose:
        cca:
          backend: debug

elasticsearch:
  datasource:
    host: localhost
    port: 9200
    fingerprint: ${ELASTIC_FINGERPRINT}
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
  query:
    timeout: 30s

  max-concurrent-requests: 2

storage:
  fstmp:
    folder: "/Users/ilakonovalov/IdeaProjects/cca-backend/tmpstorage"