version: "3.9"

services:
  frontend:
    image: turbogoosen/cca-frontend:latest
    environment:
      TZ: Europe/Moscow
    ports:
      - "3000:3000"
    restart: always
    networks:
      - esnet

  backend:
    image: turbogoosen/cca-backend:latest
    environment:
      TZ: Europe/Moscow
      SPRING_PROFILES_ACTIVE: test
      TEMP_FILESYSTEM_STORAGE: /tmp/cca-backend
    ports:
      - "8080:8080"
    volumes:
      - fsdata:/tmp/cca-backend
    restart: always
    networks:
      - esnet

  postgres:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      TZ: Europe/Moscow
      POSTGRES_DB: cca-test-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bebrapostgres
    restart: always
    networks:
      - esnet

  elastic:
    image: elasticsearch:8.13.0
    environment:
      - TZ=Europe/Moscow
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  esdata:
    driver: local
  pgdata:
    driver: local
  fsdata:
    driver: local

networks:
  esnet:
    driver: bridge