CREATE TABLE IF NOT EXISTS storages
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id INT REFERENCES datasets (id) NOT NULL,
    storage_id VARCHAR(200),
    status     VARCHAR(20),
    mode       VARCHAR(10)
)